// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Detects and highlights potentially biased language in text,
 *               assesses for hallucinations, and ideological skew, providing confidence scores.
 *
 * - detectBiasInText - A function that analyzes text for bias, hallucination, and ideological skew.
 * - DetectBiasInTextInput - The input type for the detectBiasInText function.
 * - DetectBiasInTextOutput - The return type for the detectBiasInText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectBiasInTextInputSchema = z.object({
  text: z.string().describe('The input text to analyze.'),
});
export type DetectBiasInTextInput = z.infer<typeof DetectBiasInTextInputSchema>;

const BiasDetectionResultSchema = z.object({
  biasType: z.string().describe('The type of bias detected (e.g., gender, racial, ableist).'),
  biasedPhrase: z.string().describe('The specific phrase identified as biased.'),
  confidenceScore: z.number().describe('A confidence score (0-1) indicating the likelihood of the primary bias detected for this phrase.'),
  suggestedRewrite: z.string().describe('A suggested unbiased rephrasing of the biased phrase.'),
  hallucinationScore: z.number().optional().describe('A score (0-1) indicating the likelihood of hallucination in this specific phrase. Provided if this phrase also appears to be a hallucination.'),
  ideologicalSkewScore: z.number().optional().describe('A score (0-1) indicating the degree of ideological skew in this specific phrase. Provided if this phrase also exhibits ideological skew.'),
});

const DetectBiasInTextOutputSchema = z.object({
  overallBiasScore: z.number().describe('An overall score (0-1) indicating the general level of specific biases (like gender, racial etc.) in the text.'),
  overallHallucinationScore: z.number().describe('An overall score (0-1) indicating the general level of hallucination in the entire text.'),
  overallIdeologicalSkewScore: z.number().describe('An overall score (0-1) indicating the general level of ideological skew in the entire text.'),
  biasDetections: z.array(BiasDetectionResultSchema).describe('An array of bias detection results for specific biased phrases.'),
});

export type DetectBiasInTextOutput = z.infer<typeof DetectBiasInTextOutputSchema>;

export async function detectBiasInText(input: DetectBiasInTextInput): Promise<DetectBiasInTextOutput> {
  return detectBiasInTextFlow(input);
}

const detectBiasInTextPrompt = ai.definePrompt({
  name: 'detectBiasInTextPrompt',
  input: {schema: DetectBiasInTextInputSchema},
  output: {schema: DetectBiasInTextOutputSchema},
  prompt: `You are an AI expert in identifying biased language, factual inaccuracies (hallucinations), and ideological skew. Analyze the provided text.

Your primary task is to detect and detail instances of specific biases (e.g., gender, racial, ableist).
Additionally, assess the entire text for:
1. Overall Hallucination Level: The extent to which the text contains factually incorrect, fabricated, or unsupported information.
2. Overall Ideological Skew Level: The extent to which the text demonstrates a significant leaning towards a particular political, social, or economic viewpoint, potentially misrepresenting or omitting other perspectives.

For each specific instance of BIAS detected, provide:
- biasType: The specific type of bias (e.g., gender bias, racial bias).
- biasedPhrase: The exact phrase that exhibits bias.
- confidenceScore: A confidence score between 0 and 1, indicating the likelihood of this specific bias.
- suggestedRewrite: An unbiased alternative phrasing.
- hallucinationScore: (Optional, 0-1) If this biased phrase ALSO appears to be a hallucination, provide a score for the likelihood of hallucination for this specific phrase.
- ideologicalSkewScore: (Optional, 0-1) If this biased phrase ALSO exhibits ideological skew, provide a score for the degree of skew for this specific phrase.

Text: {{{text}}}

Output should be structured as a JSON object with:
- overallBiasScore: An overall score (0-1) indicating the general level of specific biases (like gender, racial etc.) in the text.
- overallHallucinationScore: An overall score (0-1) indicating the general level of hallucination in the entire text.
- overallIdeologicalSkewScore: An overall score (0-1) indicating the general level of ideological skew in the entire text.
- biasDetections: An array of bias detection results for specific biased phrases as described above. If no specific biases are found, this array can be empty. Ensure overall scores are still provided.`,
});

const detectBiasInTextFlow = ai.defineFlow(
  {
    name: 'detectBiasInTextFlow',
    inputSchema: DetectBiasInTextInputSchema,
    outputSchema: DetectBiasInTextOutputSchema,
  },
  async input => {
    const {output} = await detectBiasInTextPrompt(input);
    return output!;
  }
);
